---
apiVersion: v1
kind: ConfigMap
metadata:
  name: cm
  namespace: default
  annotations:
    kustomize.toolkit.fluxcd.io/reconcile: disabled
data:
  hoi: dag
  bloeb: blaat
  yolo: yes!
  one-added-again: test123
